Repository SeoulSeek/Front-End, pull requests merged in 2025-04, with the labels that each got.

#19 feat: PlacePage 관광명소상세페이지 UI 구현
  src/App.jsx
  src/assets/PlacePage/Icon.png
  src/assets/PlacePage/checker.png
  src/assets/PlacePage/profile.png
  src/assets/PlacePage/sample.jpg
  src/assets/PlacePage/seoulMap.jpg
  src/assets/miniMap.png
  src/components/Input/PlaceSearchBar.module.css
  src/components/Input/SearchBar.module.css
  src/components/MiniProfile/MiniProfile.jsx
  src/components/MiniProfile/MiniProfile.module.css
  src/components/MiniProfile/PostInfo.jsx
  src/components/MiniProfile/PostInfo.module.css
  src/components/PostBox/PostBox.jsx
  src/components/PostBox/PostBox.module.css
  src/pages/PlacesPage/PlacesDetail.jsx
  src/pages/PlacesPage/PlacesDetail.module.css
  src/pages/PlacesPage/PlacesPage.jsx
  src/pages/PlacesPage/PlacesPage.module.css
  src/pages/PlacesPage/PlacesSearchPage.jsx
  src/pages/PlacesPage/PostPlacePage.jsx
Labels: feat

#21 feat: 메인화면 이미지 아이콘 추가
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.module.css
Labels: feat

#23 feat: 사이드바 개선
  src/components/Sidebar/Sidebar.jsx
Labels: feat, branch

#26 Feature/courses page
  src/App.jsx
  src/assets/CoursesPage/AiFillStar.png
  src/assets/CoursesPage/AiStar.png
  src/components/CoursesBox/CoursesBox.jsx
  src/components/CoursesBox/CoursesBox.module.css
  src/components/CoursesMobileTag/CoursesMobileTag.jsx
  src/components/CoursesMobileTag/CoursesMobileTag.module.css
  src/components/Header/Header.module.css
  src/components/Sidebar/Sidebar.module.css
  src/components/global/SortMenu/SortMenu.jsx
  src/components/global/SortMenu/SortMenu.module.css
  src/pages/CoursesPage/CoursesDetail.jsx
  src/pages/CoursesPage/CoursesDetail.module.css
  src/pages/CoursesPage/CoursesPage.jsx
  src/pages/CoursesPage/CoursesPage.module.css
Labels: feat, branch

#24 docs: 로그인 및 회원가입 페이지 디자인 수정,변경
  package-lock.json
  package.json
  src/components/Checkbox/Checkbox.jsx
  src/components/Input/Input.jsx
  src/components/Input/Input.module.css
  src/layouts/AuthLayout.jsx
  src/layouts/AuthLayout.module.css
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage.module.css
  src/pages/SigninPage/SigninPage.jsx
  src/pages/SigninPage/SigninPage.module.css
Labels: docs

#25 docs: 로딩페이지 디자인 변경, 수정
  src/assets/LoadingIcons/clock.png
  src/assets/LoadingIcons/eyes.png
  src/assets/LoadingIcons/foots.png
  src/assets/LoadingIcons/glass.png
  src/components/Loading/Loading.jsx
  src/components/Loading/Loading.module.css
Labels: docs

#28 feat: 관광명소 관련 페이지 수정 및 미니 방명록 추가
  src/App.jsx
  src/components/Input/SearchBar.module.css
  src/components/MiniPostBox/MiniPostBox.jsx
  src/components/MiniPostBox/MiniPostBox.module.css
  src/components/MiniProfile/MiniProfile.jsx
  src/components/MiniProfile/PostInfo.module.css
  src/components/PostBox/PostBox.jsx
  src/components/global/HashTag/HashTag.jsx
  src/data/dummyPosts.js
  src/pages/PlacesPage/PlacesDetail.jsx
  src/pages/PlacesPage/PlacesDetail.module.css
  src/pages/PlacesPage/PlacesPage.jsx
  src/pages/PlacesPage/PlacesPage.module.css
  src/pages/PlacesPage/PlacesSearchPage.jsx
  src/pages/PlacesPage/PostPlacePage.jsx
Labels: docs, feat

#30 feat: 404NotFound 페이지 UI 구현
  src/App.jsx
  src/assets/NotFoundPage/cloud1.png
  src/assets/NotFoundPage/cloud2.png
  src/pages/NotFoundPage/NotFoundPage.jsx
  src/pages/NotFoundPage/NotFoundPage.module.css
Labels: feat
