Repository SeoulSeek/Front-End, pull requests merged in 2025-09, with the labels that each got.

#38 Feature/header
  index.html
  public/favicon.png
  src/assets/SSFavicon.png
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
  src/components/Header/Header.module.css
  src/components/PolicyModal/PolicyModal.jsx
  src/components/PolicyModal/PolicyModal.module.css
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/Sidebar.module.css
  src/layouts/Layout.jsx
  src/layouts/Layout.module.css
  src/pages/HomePage/HomePage.module.css
Labels: feat, branch

#40 feat: 로그인 로그아웃 구현 마이페이지, 사이드바
  src/App.jsx
  src/components/LogoutModal/LogoutModal.jsx
  src/components/LogoutModal/LogoutModal.module.css
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/Sidebar.module.css
  src/contexts/AuthContext.jsx
  src/hooks/auth.js
  src/pages/MyPage/MyPage.jsx
Labels: feat

#44 feat: PlacesPage반응형 작업
  src/components/PostBox/PostBox.module.css
  src/components/global/HashTag/HashTag.jsx
  src/pages/PlacesPage/PlacesPage.jsx
  src/pages/PlacesPage/PlacesPage.module.css
  src/pages/PlacesPage/PostPlacePage.jsx
Labels: feat

#47 Feature/my page
  src/config/api.js
  src/contexts/AuthContext.jsx
Labels: bug, feat, branch
